export const GET_POKEMON_LIST = 'GET_POKEMON_LIST';
export const GET_POKEMON_LIST_SUCCESS = 'GET_POKEMON_LIST_SUCCESS';
export const GET_POKEMON_LIST_FAILURE = 'GET_POKEMON_LIST_FAILURE';

export const GET_POKEMON_DETAILS = 'GET_POKEMON_DETAILS';
export const GET_POKEMON_DETAILS_SUCCESS = 'GET_POKEMON_DETAILS_SUCCESS';
export const GET_POKEMON_DETAILS_FAILURE = 'GET_POKEMON_DETAILS_FAILURE';

export const GET_POKEMON_SPECIES = 'GET_POKEMON_SPECIES';
export const GET_POKEMON_SPECIES_SUCCESS = 'GET_POKEMON_SPECIES_SUCCESS';
export const GET_POKEMON_SPECIES_FAILURE = 'GET_POKEMON_SPECIES_FAILURE';
